#!/bin/bash
export PATH=$PATH:/usr/local/bin
touch stoptest.txt
cat /home/nodeuser/nodeapp/helloworld/app.js
SERVICE='node'
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
     /usr/local/bin/pm2 stop /home/nodeuser/nodeapp/helloworld/app.js
else
    echo "$SERVICE is not running"
fi
